FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"
ENV TERM=xterm

RUN apt update
RUN apt update && \
    apt install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata
RUN apt install -y ssh

RUN apt -y install \
    bc \
    bison \
    curl \
    flex \
    util-linux \
    make \
    time \
    perl-base \
    pkg-config \
    procps \
    libssl-dev \
    libelf-dev \
    gcc \
    binutils \
    netcat \
    git \
    magic-wormhole \
    golang  \
    gdebi   \
    mpich   \
    sshpass
