files:
- mode: '0755'
  path: gather-on-test.sh
  source: gather-on-test.sh
- mode: '0600'
  path: qemu-ssh-access
  source: qemu-ssh-access
init:
- linuxkit/init:v0.8
- linuxkit/runc:v0.8
- linuxkit/containerd:v0.8
- linuxkit/ca-certificates:v0.8
kernel:
  cmdline: console=tty0 console=ttyS0 console=ttyAMA0
  image: prasant/linux-5.15-gcov:latest
onboot:
- image: linuxkit/sysctl:v0.8
  name: sysctl
- command:
  - /sbin/dhcpcd
  - --nobackground
  - -f
  - /dhcpcd.conf
  - '-1'
  image: linuxkit/dhcpcd:v0.8
  name: dhcpcd
onshutdown:
- command:
  - /bin/echo
  - so long and thanks for all the fish
  image: busybox:latest
  name: shutdown
services:
- env:
  - INSECURE=true
  image: linuxkit/getty:v0.8
  name: getty
trust:
  org:
  - linuxkit
  - library
