files:
- mode: '0600'
  path: qemu-ssh-access
  source: qemu-ssh-access
- mode: '0755'
  path: profile.sh
  source: profile.sh
init:
- linuxkit/init:v0.8
- linuxkit/runc:v0.8
- linuxkit/containerd:v0.8
- linuxkit/ca-certificates:v0.8
kernel:
  cmdline: console=tty0 console=ttyS0 console=ttyAMA0
  image: tracks/linux-gcov:latest
onboot:
- image: linuxkit/sysctl:v0.8
  name: sysctl
- command:
  - /sbin/dhcpcd
  - --nobackground
  - -f
  - /dhcpcd.conf
  - '-1'
  image: linuxkit/dhcpcd:v0.8
  name: dhcpcd
onshutdown:
- command:
  - /bin/echo
  - so long and thanks for all the fish
  image: busybox:latest
  name: shutdown
services:
- env:
  - INSECURE=true
  image: linuxkit/getty:v0.8
  name: getty
- binds:
  - /etc/resolv.conf:/etc/resolv.conf
  - /qemu-ssh-access:/root/.ssh/id_ed25519
  - /profile.sh:/root.profile.sh
  capabilities:
  - ALL
  command:
  - /bin/sh
  - -c
  - /usr/bin/sleep infinity
  env:
  - UBUNTU=true
  - ACTION=profile
  image: tracks/ubuntu:latest
  name: tracks/ubuntu
trust:
  org:
  - linuxkit
  - library
