#!/bin/bash

set -euo

sed -i "s|image: prasant/linux-.*|image: prasant/linux-5.15-cfi-$1|" linuxkit.yml

linuxkit build -disable-content-trust linuxkit.yml
linuxkit run qemu -publish 8080:80 -mem 32768 -cpus 8 linuxkit
