#!/bin/bash

set -euo

FEATURE=$1

if [ -z "$FEATURE" ]; then
        echo "usage: benchmark [ full | none | selective ]"
            exit 1
fi

sed -i '/name: ubuntu/,/command/{s|command.*|command: ["/bin/sh", "-c", "/bin/sleep infinity"]|}' linuxkit.yml

./boot $1
